In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e #

2.718281828459045

In [4]:
math.inf

inf

In [8]:
math.ceil(7.25) #ceiling func rounds to nearest highest integer

8

In [7]:
math.floor(2.89) #floor rounds to lowest integer

2

In [9]:
float_list=[0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,]

In [10]:
sum(float_list)

0.9999999999999999

In [11]:
math.fsum(float_list) #

1.0

In [12]:
math.gcd(30,20) #greatest common denominator of values

10

In [14]:
math.gcd(156,96)

12

In [16]:
import numpy as np #working w/ large arrays

In [17]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [19]:
some_array = np.array(some_list)
type(some_array) #"nd" stands for multi-dimensional or "n" dimensional in py speak

numpy.ndarray

In [20]:
some_array #same list but now an array

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#gives five elements in array
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [23]:
#An "Arange" starts from 0
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
#reshape array to be a 2x4 N dimensional array
reshape_array = range_array.reshape(2,4)
reshape_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
#can alter existing array as long as number of elements match up
reshape_array = range_array.reshape(4,2)
reshape_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
reshape_array = range_array.reshape(4,2,2)
reshape_array

ValueError: cannot reshape array of size 8 into shape (4,2,2)

In [27]:
random_array = np.random.random((4,5))
random_array #randomly generates values

array([[0.50860762, 0.30615703, 0.66401614, 0.70903077, 0.56826121],
       [0.01258408, 0.53749539, 0.86785383, 0.72052216, 0.53386574],
       [0.39806608, 0.04988302, 0.59797459, 0.33351941, 0.82347304],
       [0.14967707, 0.19777994, 0.30038257, 0.71817076, 0.22914378]])

In [28]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
mean = np.mean(range_array)
mean

3.5

In [30]:
var = np.var(range_array)
var

5.25

In [32]:
std = np.std(range_array)
std

2.29128784747792

In [33]:
import pandas as pd #data in rows and columns

In [39]:
df = pd.DataFrame({
    "Name":["John","Alice","Bob","Eileen","Rob"],
    "Gender":["Male","Female","Male","Female","Male"],
    "Age":[45,20,30,14,67]
})

In [40]:
df

Name  Gender  Age
0    John    Male   45
1   Alice  Female   20
2     Bob    Male   30
3  Eileen  Female   14
4     Rob    Male   67

In [42]:
#describe() provides a quick statistical overview of all numerical columns in your pandas DataFrame
df.describe()

Age
count   5.000000
mean   35.200000
std    21.300235
min    14.000000
25%    20.000000
50%    30.000000
75%    45.000000
max    67.000000

In [43]:
subset_df = df[["Name","Age"]]
subset_df

Name  Age
0    John   45
1   Alice   20
2     Bob   30
3  Eileen   14
4     Rob   67

In [44]:
groupby_df = df.groupby(by="Gender").count()
groupby_df.head()

Name  Age
Gender           
Female     2    2
Male       3    3