In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\g_lee\\Python Practice'

In [5]:
open('price.csv')

<_io.TextIOWrapper name='price.csv' mode='r' encoding='cp1252'>

In [4]:
os.listdir()

['.ipynb_checkpoints',
 '00_Practice_with_SimpleExpressions_Arithmetic.ipynb',
 '01_Practice_Py_Code.ipynb',
 '02_Practice_with_Lists.ipynb',
 '03_Practice_with_Tuples.ipynb',
 '04_Practice_with_Dictionaries.ipynb',
 '05_Practice_with_If_Statements.ipynb',
 '06_Practice_with_ForLoops.ipynb',
 '07_Practice_with_WhileLoops.ipynb',
 '08_Practice_with_BreakContinuePass.ipynb',
 '09_Practice_with_FunctionsInputsArgumentsReturnValues.ipynb',
 '10_Practice_with_Functions_Continued.ipynb',
 '11_Practice_with_ImportingModules.ipynb',
 '12_Practice_with_CommandLineAndEnvironVariables.ipynb',
 '13_Practice_with_Files.ipynb',
 'BasicTypesInPython.ipynb',
 'IRIS.csv',
 'myscript.py',
 'newfile.py',
 'price.csv',
 'price.py',
 'saved_iris_df.csv',
 'sin_curve.ipynb',
 'Strings.ipynb',
 'UnderstandingJupyter.ipynb',
 'UnderstandingJupyterPy3.ipynb',
 'Variables.ipynb',
 'WorkingWithJupyterNotebooks.ipynb']

In [6]:
file = open('price.csv')
file

<_io.TextIOWrapper name='price.csv' mode='r' encoding='cp1252'>

In [7]:
#FILE handle acts as a pointer to the file
file.read()

'Things,Quantity,Total_Price\nSpoon,105.0,1050\nPlate,78.0,2250\nCup,90.0,1550\nFork,NaN,890\nBread,21.0,620\nJuice,85.0,2125\nBiscuit,15.0,312\nCake,18.0,523\nChocolate,100.0,100'

In [8]:
#Since the pointer already read the file, it has nothing else to read since it is "at the end"
file.read()

''

In [9]:
#The "SEEK" commnand points the file handle back to the very first byte position in the file, or zero (0)
file.seek(0)

0

In [10]:
file.read()

'Things,Quantity,Total_Price\nSpoon,105.0,1050\nPlate,78.0,2250\nCup,90.0,1550\nFork,NaN,890\nBread,21.0,620\nJuice,85.0,2125\nBiscuit,15.0,312\nCake,18.0,523\nChocolate,100.0,100'

In [12]:
file.seek(0)

0

In [13]:
#Just want to read the first 5 bytes
file.read(5)

'Thing'

In [14]:
#This will read 6 bytes, starting at the 5th byte
file.read(6)

's,Quan'

In [15]:
#TELL reveals the byte position that the READ command is
file.tell()

11

In [16]:
file.read()

'tity,Total_Price\nSpoon,105.0,1050\nPlate,78.0,2250\nCup,90.0,1550\nFork,NaN,890\nBread,21.0,620\nJuice,85.0,2125\nBiscuit,15.0,312\nCake,18.0,523\nChocolate,100.0,100'

In [17]:
#After opening a file, you need to close it to prevent corruption
file.close()

In [18]:
file.read()

ValueError: I/O operation on closed file.

In [19]:
file = open('price.csv')
file

<_io.TextIOWrapper name='price.csv' mode='r' encoding='cp1252'>

In [20]:
file.read()

'Things,Quantity,Total_Price\nSpoon,105.0,1050\nPlate,78.0,2250\nCup,90.0,1550\nFork,NaN,890\nBread,21.0,620\nJuice,85.0,2125\nBiscuit,15.0,312\nCake,18.0,523\nChocolate,100.0,100'

In [21]:
file.seek(0)

0

In [22]:
#READLINE reads the file one line at a time
file.readline()

'Things,Quantity,Total_Price\n'

In [23]:
file.readline()

'Spoon,105.0,1050\n'

In [24]:
file.readline()

'Plate,78.0,2250\n'

In [25]:
file.readline()

'Cup,90.0,1550\n'

In [26]:
file.seek(0)

0

In [27]:
#Readlines returns all the lines in your file in the form of a py List
file.readlines()

['Things,Quantity,Total_Price\n',
 'Spoon,105.0,1050\n',
 'Plate,78.0,2250\n',
 'Cup,90.0,1550\n',
 'Fork,NaN,890\n',
 'Bread,21.0,620\n',
 'Juice,85.0,2125\n',
 'Biscuit,15.0,312\n',
 'Cake,18.0,523\n',
 'Chocolate,100.0,100']

In [28]:
file.close()

In [29]:
file.read()

ValueError: I/O operation on closed file.

In [55]:
#"a" appends to existing file
with open('IRIS.csv', 'a') as f:
    more_flowers = f.write("Roses")
    
    print("Number or characters:",more_flowers)

Number or characters: 5


In [31]:
file.read()

ValueError: I/O operation on closed file.

In [32]:
file = open('IRIS.csv')
file

<_io.TextIOWrapper name='IRIS.csv' mode='r' encoding='cp1252'>

In [33]:
file.read()

'sepal_length,sepal_width,petal_length,petal_width,species\n5.1,3.5,1.4,0.2,Iris-setosa\n4.9,3.0,1.4,0.2,Iris-setosa\n4.7,3.2,1.3,0.2,Iris-setosa\n4.6,3.1,1.5,0.2,Iris-setosa\n5.0,3.6,1.4,0.2,Iris-setosa\n5.0,3.5,1.5,0.2,Iris-setosaRoses'

In [35]:
file.seek(0)

0

In [36]:
file.readlines()

['sepal_length,sepal_width,petal_length,petal_width,species\n',
 '5.1,3.5,1.4,0.2,Iris-setosa\n',
 '4.9,3.0,1.4,0.2,Iris-setosa\n',
 '4.7,3.2,1.3,0.2,Iris-setosa\n',
 '4.6,3.1,1.5,0.2,Iris-setosa\n',
 '5.0,3.6,1.4,0.2,Iris-setosa\n',
 '5.0,3.5,1.5,0.2,Iris-setosaRoses']

In [37]:
file.close()

In [38]:
with open("sportscars.txt",'w') as f:
    f.write("Mustang")

In [42]:
!cat sportscars.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [43]:
file = open('sportscars.txt')
file

<_io.TextIOWrapper name='sportscars.txt' mode='r' encoding='cp1252'>

In [44]:
file.read()

'Mustang'

In [45]:
sports_cars = ['Agera','Regera','Chiron','Veyron']

In [46]:
with open('sportscars.txt','w') as f:
    for car in sports_cars:
        f.write(car)

In [48]:
file.seek(0)

0

In [49]:
file.read()

'AgeraRegeraChironVeyron'

In [50]:
#adding breaks
with open('sportscars.txt','w') as f:
    for car in sports_cars:
        f.write(car + '\n')

In [51]:
file.seek(0)

0

In [52]:
file.read()

'Agera\nRegera\nChiron\nVeyron\n'

In [53]:
file.seek(0)

0

In [54]:
file.readlines()

['Agera\n', 'Regera\n', 'Chiron\n', 'Veyron\n']

In [56]:
os.getcwd()

'C:\\Users\\g_lee\\Python Practice'

In [57]:
os.listdir()

['.ipynb_checkpoints',
 '00_Practice_with_SimpleExpressions_Arithmetic.ipynb',
 '01_Practice_Py_Code.ipynb',
 '02_Practice_with_Lists.ipynb',
 '03_Practice_with_Tuples.ipynb',
 '04_Practice_with_Dictionaries.ipynb',
 '05_Practice_with_If_Statements.ipynb',
 '06_Practice_with_ForLoops.ipynb',
 '07_Practice_with_WhileLoops.ipynb',
 '08_Practice_with_BreakContinuePass.ipynb',
 '09_Practice_with_FunctionsInputsArgumentsReturnValues.ipynb',
 '10_Practice_with_Functions_Continued.ipynb',
 '11_Practice_with_ImportingModules.ipynb',
 '12_Practice_with_CommandLineAndEnvironVariables.ipynb',
 '13_Practice_with_Files.ipynb',
 'BasicTypesInPython.ipynb',
 'IRIS.csv',
 'myscript.py',
 'newfile.py',
 'price.csv',
 'price.py',
 'saved_iris_df.csv',
 'sin_curve.ipynb',
 'sportscars.txt',
 'Strings.ipynb',
 'UnderstandingJupyter.ipynb',
 'UnderstandingJupyterPy3.ipynb',
 'Variables.ipynb',
 'WorkingWithJupyterNotebooks.ipynb']

In [59]:
import csv

with open ("price.csv",'r') as f:
    csv_reader=csv.reader(f)
    for price in csv_reader:
        print(price)

['Things', 'Quantity', 'Total_Price']
['Spoon', '105.0', '1050']
['Plate', '78.0', '2250']
['Cup', '90.0', '1550']
['Fork', 'NaN', '890']
['Bread', '21.0', '620']
['Juice', '85.0', '2125']
['Biscuit', '15.0', '312']
['Cake', '18.0', '523']
['Chocolate', '100.0', '100']


In [61]:
#If csv file has headings use DictReader to parse into tuples

with open ("price.csv",'r') as f:
    csv_reader=csv.DictReader(f)
    for price in csv_reader:
        print(price)

OrderedDict([('Things', 'Spoon'), ('Quantity', '105.0'), ('Total_Price', '1050')])
OrderedDict([('Things', 'Plate'), ('Quantity', '78.0'), ('Total_Price', '2250')])
OrderedDict([('Things', 'Cup'), ('Quantity', '90.0'), ('Total_Price', '1550')])
OrderedDict([('Things', 'Fork'), ('Quantity', 'NaN'), ('Total_Price', '890')])
OrderedDict([('Things', 'Bread'), ('Quantity', '21.0'), ('Total_Price', '620')])
OrderedDict([('Things', 'Juice'), ('Quantity', '85.0'), ('Total_Price', '2125')])
OrderedDict([('Things', 'Biscuit'), ('Quantity', '15.0'), ('Total_Price', '312')])
OrderedDict([('Things', 'Cake'), ('Quantity', '18.0'), ('Total_Price', '523')])
OrderedDict([('Things', 'Chocolate'), ('Quantity', '100.0'), ('Total_Price', '100')])


In [62]:
#Pandas still the best python library to use with CSV files
import pandas as pd

In [64]:
#Contents of csv will be read as a dataframe with the headings parsed above the line
df = pd.read_csv('price.csv')
df

Things  Quantity  Total_Price
0      Spoon     105.0         1050
1      Plate      78.0         2250
2        Cup      90.0         1550
3       Fork       NaN          890
4      Bread      21.0          620
5      Juice      85.0         2125
6    Biscuit      15.0          312
7       Cake      18.0          523
8  Chocolate     100.0          100

In [65]:
import json

In [71]:
dogs_and_ages = {"Oba":8.9,
                "Moje":4.5,
                "Nemo":1.25}
dogs_and_ages

{'Oba': 8.9, 'Moje': 4.5, 'Nemo': 1.25}

In [67]:
#Converts dictionary to JSON string
json_string = json.dumps(dogs_and_ages)
json_string

'{"Oba": 8.9, "Moje": 4.5, "Nemo": 1.25}'

In [68]:
type(json_string)

str

In [69]:
#Can use this function to convert JSON data into Python Dictionary (Step 1
dogs_and_ages_string = """
{"Oba": 8.9, "Moje": 4.5, "Nemo": 1.25}
"""

In [70]:
#Step 2 converting JSON string into python dictionary
dogs_and_ages_dict = json.loads(dogs_and_ages_string)
dogs_and_ages_dict

{'Oba': 8.9, 'Moje': 4.5, 'Nemo': 1.25}

In [72]:
type(dogs_and_ages_dict)

dict

In [74]:
#Creating JSON file using DUMP command
with open("dogs_and_ages.json",'w') as dog_file:
    json.dump(dogs_and_ages_dict,dog_file)

In [75]:
os.listdir()

['.ipynb_checkpoints',
 '00_Practice_with_SimpleExpressions_Arithmetic.ipynb',
 '01_Practice_Py_Code.ipynb',
 '02_Practice_with_Lists.ipynb',
 '03_Practice_with_Tuples.ipynb',
 '04_Practice_with_Dictionaries.ipynb',
 '05_Practice_with_If_Statements.ipynb',
 '06_Practice_with_ForLoops.ipynb',
 '07_Practice_with_WhileLoops.ipynb',
 '08_Practice_with_BreakContinuePass.ipynb',
 '09_Practice_with_FunctionsInputsArgumentsReturnValues.ipynb',
 '10_Practice_with_Functions_Continued.ipynb',
 '11_Practice_with_ImportingModules.ipynb',
 '12_Practice_with_CommandLineAndEnvironVariables.ipynb',
 '13_Practice_with_Files.ipynb',
 'BasicTypesInPython.ipynb',
 'dogs_and_ages.json',
 'IRIS.csv',
 'myscript.py',
 'newfile.py',
 'price.csv',
 'price.py',
 'saved_iris_df.csv',
 'sin_curve.ipynb',
 'sportscars.txt',
 'Strings.ipynb',
 'UnderstandingJupyter.ipynb',
 'UnderstandingJupyterPy3.ipynb',
 'Variables.ipynb',
 'WorkingWithJupyterNotebooks.ipynb']

In [76]:
file.close()

In [79]:
file = open('dogs_and_ages.json')
file

<_io.TextIOWrapper name='dogs_and_ages.json' mode='r' encoding='cp1252'>

In [80]:
file.read()

'{"Oba": 8.9, "Moje": 4.5, "Nemo": 1.25}'

In [81]:
#Can also read the JSON file this way
with open ('dogs_and_ages.json','r') as dog_file:
    file_json = json.load(dog_file)

In [82]:
file_json

{'Oba': 8.9, 'Moje': 4.5, 'Nemo': 1.25}

In [2]:
!jupyter --version

jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.6.0
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3


In [1]:
!jupyter --version

jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.3
ipython          : 7.13.0
ipykernel        : 5.2.1
jupyter client   : 6.1.3
jupyter lab      : 2.1.1
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3


In [1]:
dir(sample_array)

NameError: name 'sample_array' is not defined

In [2]:
import numpy as np
sample_array = np.array([0,0,7])
type(sample_array)

numpy.ndarray

In [3]:
dir(sample_array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [1]:
import numpy as np

In [3]:
# Use "Delimiter" command to load files that were not created by Numpy code
gene_np = np.loadtxt('Data_Files\gene.txt',delimiter=',')
gene_np

array([[0., 4., 5.],
       [8., 1., 4.],
       [7., 3., 9.],
       [2., 0., 7.],
       [4., 5., 8.]])

In [5]:
#To specify certain columns to load rather than the whole file. This example is only loading the first (0) and last(2) columns
gene_np = np.loadtxt('Data_Files/gene.txt',delimiter=',',usecols=(0,2))
gene_np

array([[0., 5.],
       [8., 4.],
       [7., 9.],
       [2., 7.],
       [4., 8.]])

In [6]:
# This causes an error b/c there are string values in the file where integers are expected
sportscars_np = np.loadtxt('Data_Files\sportscars.txt',delimiter=',')
sportscars_np

ValueError: could not convert string to float: 'Agera'

In [9]:
#Usecols command allows you to bypass string values in a column
sportscars_np = np.loadtxt('Data_Files\sportscars.txt',delimiter=',',usecols=(1,2))
sportscars_np

array([[  400., 75000.],
       [  560., 49000.],
       [  365., 39875.],
       [  411., 86000.]])

In [10]:
# What if they're in your header now
gene_np = np.loadtxt('Data_Files\gene.txt',delimiter=',')
gene_np

ValueError: could not convert string to float: 'ID'

In [12]:
# Use "skiprows". Can also use "skipfooter" if there is data to be left out at the end of the file
gene_np = np.loadtxt('Data_Files\gene.txt',delimiter=',',skiprows=1)
gene_np

array([[0., 4., 5.],
       [8., 1., 4.],
       [7., 3., 9.],
       [2., 0., 7.],
       [4., 5., 8.]])

In [13]:
gene_np.dtype

dtype('float64')

In [18]:
# Convert option
def increase(the_ID):
    return int(the_ID) + 100

gene_increase = np.loadtxt('Data_Files\gene.txt',delimiter=',',skiprows=1,
                          converters={0:increase})
gene_increase

array([[100.,   4.,   5.],
       [108.,   1.,   4.],
       [107.,   3.,   9.],
       [102.,   0.,   7.],
       [104.,   5.,   8.]])

In [21]:
# Numpy "genfromtext" function replaces missing or non-numerical values with 'nan' or 'not a number'
gene_missing_value = np.genfromtxt('Data_Files/gene_missing.txt',
                                   delimiter=',')
gene_missing_value

array([[nan, nan, nan],
       [ 0.,  4.,  5.],
       [ 8.,  1.,  4.],
       [ 7.,  3.,  9.],
       [ 2.,  0., nan],
       [ 4.,  5.,  8.]])

In [22]:
# So to avoid nan values in first row, use 'skip_header' function
gene_missing_value = np.genfromtxt('Data_Files/gene_missing.txt',
                                   delimiter=',',skip_header=1)
gene_missing_value

array([[ 0.,  4.,  5.],
       [ 8.,  1.,  4.],
       [ 7.,  3.,  9.],
       [ 2.,  0., nan],
       [ 4.,  5.,  8.]])

In [23]:
#The Python CSV library implements classes to read (and write) tabular data in csv format
import csv

In [24]:
dir(csv)

['Dialect',
 'DictReader',
 'DictWriter',
 'Error',
 'QUOTE_ALL',
 'QUOTE_MINIMAL',
 'QUOTE_NONE',
 'QUOTE_NONNUMERIC',
 'Sniffer',
 'StringIO',
 '_Dialect',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 'excel',
 'excel_tab',
 'field_size_limit',
 'get_dialect',
 'list_dialects',
 're',
 'reader',
 'register_dialect',
 'unix_dialect',
 'unregister_dialect',
 'writer']

In [25]:
csv.list_dialects()
['excel-tab','excel']

['excel-tab', 'excel']

In [28]:
with open('Data_Files/adsmall.csv') as csv_file:
    csv_reader = csv.reader(csv_file,delimiter=',',quotechar='"')
    for row in csv_reader:
        print(row)

['68.95', '35', '61833.9', '256.09', 'Cloned 5thgeneration orchestration', 'Wrightburgh', '0', 'Tunisia', '3/27/2016 0:53', '0']
['80.23', '31', '68441.85', '193.77', 'Monitored national standardization', 'West Jodi', '1', 'Nauru', '4/4/2016 1:39', '0']
['69.47', '26', '59785.94', '236.5', 'Organic bottom-line service-desk', 'Davidton', '0', 'San Marino', '3/13/2016 20:35', '0']
['74.15', '29', '54806.18', '245.89', 'Triple-buffered reciprocal time-frame', 'West Terrifurt', '1', 'Italy', '1/10/2016 2:31', '0']
['68.37', '35', '73889.99', '225.58', 'Robust logistical utilization', 'South Manuel', '0', 'Iceland', '6/3/2016 3:36', '0']
['59.99', '23', '59761.56', '226.74', 'Sharable client-driven software', 'Jamieberg', '1', 'Norway', '5/19/2016 14:30', '0']
['88.91', '33', '53852.85', '208.36', 'Enhanced dedicated support', 'Brandonstad', '0', 'Myanmar', '1/28/2016 20:59', '0']
['66', '48', '24593.33', '131.76', 'Reactive local challenge', 'Port Jefferybury', '1', 'Australia', '3/7/2016 

In [29]:
field_names = ['TimeSpent','Age','AreaIncome','DailyInternetUsage','AdHeadLine','City','Male','Country','Timestamp','Clicked']

In [33]:
#Reading with "DictReader" function
with open('Data_Files/adsmall.csv') as csv_file:
    csv_dict_reader = csv.DictReader(csv_file,fieldnames=field_names)
    for row in csv_dict_reader:
        print(row['Age'] + ' year olds spends ' + row['TimeSpent'] + ' minutes on the internet before clicking on an Ad.')

35 year olds spends 68.95 minutes on the internet before clicking on an Ad.
31 year olds spends 80.23 minutes on the internet before clicking on an Ad.
26 year olds spends 69.47 minutes on the internet before clicking on an Ad.
29 year olds spends 74.15 minutes on the internet before clicking on an Ad.
35 year olds spends 68.37 minutes on the internet before clicking on an Ad.
23 year olds spends 59.99 minutes on the internet before clicking on an Ad.
33 year olds spends 88.91 minutes on the internet before clicking on an Ad.
48 year olds spends 66 minutes on the internet before clicking on an Ad.
30 year olds spends 74.53 minutes on the internet before clicking on an Ad.
20 year olds spends 69.88 minutes on the internet before clicking on an Ad.
49 year olds spends 47.64 minutes on the internet before clicking on an Ad.
37 year olds spends 83.07 minutes on the internet before clicking on an Ad.
48 year olds spends 69.57 minutes on the internet before clicking on an Ad.
24 year olds sp

### Pay attention to "Quote Minimals" to your csv source files if there is an additional comma inputted as a single field value

In [28]:
# Loading CSV from URL schemes (http, ftp, etc)
import pandas as pd

remote_file = 'https://raw.githubusercontent.com/genelee9-vc/python/master/GA_COVID.csv'
#Below if GitHub repo is not public
#'https://raw.githubusercontent.com/genelee9-vc/python/master/GA_COVID.csv?token=AMWQI4RR3PZDVRCYP7XBSZC6X5COU'

In [29]:
posts_url = pd.read_csv(remote_file,header=None)

posts_url.head()

0      1          2       3              4               5  \
0       Date  state   positive   death   hospitalized   deathIncrease   
1   5/1/2020     GA      27270    1154           5269              34   
2  4/30/2020     GA      26155    1120           5156              27   
3  4/29/2020     GA      25572    1093           5056              67   
4  4/28/2020     GA      24615    1026           4814              55   

                       6                  7  
0   hospitalizedIncrease   positiveIncrease  
1                    113               1115  
2                    100                583  
3                    242                957  
4                    133                702

In [30]:
#To specify the exact number of rows you want to read
posts_small = pd.read_csv(remote_file,nrows=8)
posts_small

Date state   positive   death   hospitalized   deathIncrease  \
0   5/1/2020    GA      27270    1154           5269              34   
1  4/30/2020    GA      26155    1120           5156              27   
2  4/29/2020    GA      25572    1093           5056              67   
3  4/28/2020    GA      24615    1026           4814              55   
4  4/27/2020    GA      23913     971           4681              59   
5  4/26/2020    GA      23401     912           4359               8   
6  4/25/2020    GA      22695     904           4326              12   
7  4/24/2020    GA      22147     892           4221              20   

    hospitalizedIncrease   positiveIncrease  
0                    113               1115  
1                    100                583  
2                    242                957  
3                    133                702  
4                    322                512  
5                     33                706  
6                    105                548  
7                    152                635

In [31]:
#To specify the exact number of rows to skip that you want to read
posts_small_skiprows = pd.read_csv(remote_file,nrows=10,skiprows=5)
posts_small_skiprows

4/27/2020  GA  23913  971  4681  59  322   512
0  4/26/2020  GA  23401  912  4359   8   33   706
1  4/25/2020  GA  22695  904  4326  12  105   548
2  4/24/2020  GA  22147  892  4221  20  152   635
3  4/23/2020  GA  21512  872  4069  36  110   772
4  4/22/2020  GA  20740  836  3959  37  180   859
5  4/21/2020  GA  19881  799  3779  66  229   934
6  4/20/2020  GA  18947  733  3550  46   86   646
7  4/19/2020  GA  18301  687  3464  14   44   632
8  4/18/2020  GA  17669  673  3420  23   96   475
9  4/17/2020  GA  17194  650  3324  63  216  1525

### As you can see, the code skips the first 5 lines of data and starts index 0,1,2 etc at the 6th line in the CSV file

In [32]:
# If you want to just pull in odd rows, use "LAMBDA" calculus feature in Python
posts_odd = pd.read_csv(remote_file,skiprows=lambda x: x % 2 !=0)
posts_odd.head()

Date state   positive   death   hospitalized   deathIncrease  \
0  4/30/2020    GA      26155  1120.0         5156.0              27   
1  4/28/2020    GA      24615  1026.0         4814.0              55   
2  4/26/2020    GA      23401   912.0         4359.0               8   
3  4/24/2020    GA      22147   892.0         4221.0              20   
4  4/22/2020    GA      20740   836.0         3959.0              37   

    hospitalizedIncrease   positiveIncrease  
0                    100                583  
1                    133                702  
2                     33                706  
3                    152                635  
4                    180                859

In [33]:
posts_columns = pd.read_csv(remote_file,usecols=[0,3,5])
posts_columns.head()

Date   death   deathIncrease
0   5/1/2020  1154.0            34.0
1  4/30/2020  1120.0            27.0
2  4/29/2020  1093.0            67.0
3  4/28/2020  1026.0            55.0
4  4/27/2020   971.0            59.0

In [36]:
# Can't run this on a csv file that you did not create in this app
remote_file.info()

AttributeError: 'str' object has no attribute 'info'

In [38]:
# To understand the datatype of your files on specific columns
pd.read_csv(remote_file,usecols=[0,1,2,4,6]).dtypes

Date                      object
state                     object
 positive                  int64
 hospitalized            float64
 hospitalizedIncrease    float64
dtype: object

In [42]:
posts_tags=pd.read_csv(remote_file,usecols=[0,1,2,4,6])
posts_tags.iloc[1]

Date                     4/30/2020
state                           GA
 positive                    26155
 hospitalized                 5156
 hospitalizedIncrease          100
Name: 1, dtype: object